---
- name: Converge
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root

  tasks:
    - name: configure user
      ansible.builtin.include_role:
        name: user
      vars:
        user_name: new_user
        user_password: superSekret
        user_authorized_keys:
          new_user: ssh-rsa NEWUSERPUBKEY== new_user
          admin_user: ssh-rsa ADMINUSERPUBKEY== admin_user
