---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: user-noble
    image: ubuntu:noble
  - name: user-trixie
    image: debian:trixie
provisioner:
  name: ansible
verifier:
  name: testinfra
