---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: user-focal
    image: ubuntu:focal
  - name: user-buster
    image: debian:buster
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
